### ISSUE TITLE
plugin breaks dodge 

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/godot_feagi_integration#12]
Without plugin, dodge is able to running just fine. When it comes to plugin, it got frozen

**Comment by Kakcalu13** [comment]
I have hard time to troubleshooting this since only newest OS Mac has that issue

**Comment by Amir-Rasteg** [comment]
To clear up further confusion:

testing chrome / firefox on IOS is irrelevant, since apple mandates that all IOS browsers use safari under the hood. Ergo all issues reported on IOS are from safari

As far as I can tell, this issue is safari specific. Does this line up to what others have been seeing?

To be more precise, it seems to be triggered by the screen recording function, but theres not much I can do to simplify that. 

This is likely an Apple issue

**Comment by Kakcalu13** [comment]
https://github.com/godotengine/godot/issues/98325
